[2022-11-29 02:10:03,176] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: Covid_dags.getDataToLocal manual__2022-11-29T02:10:02.564387+00:00 [queued]>
[2022-11-29 02:10:03,187] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: Covid_dags.getDataToLocal manual__2022-11-29T02:10:02.564387+00:00 [queued]>
[2022-11-29 02:10:03,187] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 02:10:03,187] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-11-29 02:10:03,187] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 02:10:03,202] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): getDataToLocal> on 2022-11-29 02:10:02.564387+00:00
[2022-11-29 02:10:03,207] {standard_task_runner.py:52} INFO - Started process 100 to run task
[2022-11-29 02:10:03,211] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Covid_dags', 'getDataToLocal', 'manual__2022-11-29T02:10:02.564387+00:00', '--job-id', '834', '--raw', '--subdir', 'DAGS_FOLDER/dbtest.py', '--cfg-path', '/tmp/tmpmwqv3o14', '--error-file', '/tmp/tmp5ug9qd0h']
[2022-11-29 02:10:03,212] {standard_task_runner.py:77} INFO - Job 834: Subtask getDataToLocal
[2022-11-29 02:10:03,270] {logging_mixin.py:109} INFO - Running <TaskInstance: Covid_dags.getDataToLocal manual__2022-11-29T02:10:02.564387+00:00 [running]> on host acb48b0a6e0d
[2022-11-29 02:10:03,314] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Covid_dags
AIRFLOW_CTX_TASK_ID=getDataToLocal
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T02:10:02.564387+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-29T02:10:02.564387+00:00
[2022-11-29 02:10:19,025] {python.py:175} INFO - Done. Returned value was: None
[2022-11-29 02:10:19,034] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=Covid_dags, task_id=getDataToLocal, execution_date=20221129T021002, start_date=20221129T021003, end_date=20221129T021019
[2022-11-29 02:10:19,076] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-29 02:10:19,109] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
