[2022-11-29 02:20:02,745] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: Covid_dags.getDataToLocal manual__2022-11-29T02:20:01.709615+00:00 [queued]>
[2022-11-29 02:20:02,758] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: Covid_dags.getDataToLocal manual__2022-11-29T02:20:01.709615+00:00 [queued]>
[2022-11-29 02:20:02,758] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 02:20:02,758] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-11-29 02:20:02,758] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 02:20:02,769] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): getDataToLocal> on 2022-11-29 02:20:01.709615+00:00
[2022-11-29 02:20:02,773] {standard_task_runner.py:52} INFO - Started process 580 to run task
[2022-11-29 02:20:02,776] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Covid_dags', 'getDataToLocal', 'manual__2022-11-29T02:20:01.709615+00:00', '--job-id', '856', '--raw', '--subdir', 'DAGS_FOLDER/dbtest.py', '--cfg-path', '/tmp/tmpusv61zdk', '--error-file', '/tmp/tmp9dwsvn0d']
[2022-11-29 02:20:02,777] {standard_task_runner.py:77} INFO - Job 856: Subtask getDataToLocal
[2022-11-29 02:20:02,818] {logging_mixin.py:109} INFO - Running <TaskInstance: Covid_dags.getDataToLocal manual__2022-11-29T02:20:01.709615+00:00 [running]> on host acb48b0a6e0d
[2022-11-29 02:20:02,859] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Covid_dags
AIRFLOW_CTX_TASK_ID=getDataToLocal
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T02:20:01.709615+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-29T02:20:01.709615+00:00
[2022-11-29 02:20:05,284] {python.py:175} INFO - Done. Returned value was: None
[2022-11-29 02:20:05,293] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=Covid_dags, task_id=getDataToLocal, execution_date=20221129T022001, start_date=20221129T022002, end_date=20221129T022005
[2022-11-29 02:20:05,316] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-29 02:20:05,343] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
