[2022-11-29 13:47:35,076] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: vaccine_dags.transformData manual__2022-11-29T13:47:30.891053+00:00 [queued]>
[2022-11-29 13:47:35,088] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: vaccine_dags.transformData manual__2022-11-29T13:47:30.891053+00:00 [queued]>
[2022-11-29 13:47:35,088] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 13:47:35,088] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-11-29 13:47:35,089] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 13:47:35,109] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): transformData> on 2022-11-29 13:47:30.891053+00:00
[2022-11-29 13:47:35,115] {standard_task_runner.py:52} INFO - Started process 214 to run task
[2022-11-29 13:47:35,120] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'vaccine_dags', 'transformData', 'manual__2022-11-29T13:47:30.891053+00:00', '--job-id', '1143', '--raw', '--subdir', 'DAGS_FOLDER/vaccine.py', '--cfg-path', '/tmp/tmpz1o5m_q6', '--error-file', '/tmp/tmph5wa9tt6']
[2022-11-29 13:47:35,121] {standard_task_runner.py:77} INFO - Job 1143: Subtask transformData
[2022-11-29 13:47:35,186] {logging_mixin.py:109} INFO - Running <TaskInstance: vaccine_dags.transformData manual__2022-11-29T13:47:30.891053+00:00 [running]> on host acb48b0a6e0d
[2022-11-29 13:47:35,244] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=vaccine_dags
AIRFLOW_CTX_TASK_ID=transformData
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T13:47:30.891053+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-29T13:47:30.891053+00:00
[2022-11-29 13:47:35,282] {python.py:175} INFO - Done. Returned value was:                key  ... jumlah_jumlah_vaksinasi_2_kum
0    1612137600000  ...                             0
1    1612224000000  ...                             0
2    1612310400000  ...                             0
3    1612396800000  ...                             0
4    1612483200000  ...                             0
..             ...  ...                           ...
662  1669334400000  ...                     172384615
663  1669420800000  ...                     172384615
664  1669507200000  ...                     172384615
665  1669593600000  ...                     174119714
666  1669680000000  ...                     174119714

[667 rows x 7 columns]
[2022-11-29 13:47:35,313] {xcom.py:448} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2022-11-29 13:47:35,314] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2151, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 155, in set
    value=cls.serialize_value(value),
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 445, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2022-11-29 13:47:35,332] {taskinstance.py:1282} INFO - Marking task as UP_FOR_RETRY. dag_id=vaccine_dags, task_id=transformData, execution_date=20221129T134730, start_date=20221129T134735, end_date=20221129T134735
[2022-11-29 13:47:35,348] {standard_task_runner.py:92} ERROR - Failed to execute job 1143 for task transformData
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2151, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 155, in set
    value=cls.serialize_value(value),
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 445, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2022-11-29 13:47:35,373] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-11-29 13:47:35,432] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
