[2022-11-29 01:43:33,744] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: Covid_dags.getDataToLocal manual__2022-11-29T01:43:32.331381+00:00 [queued]>
[2022-11-29 01:43:33,769] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: Covid_dags.getDataToLocal manual__2022-11-29T01:43:32.331381+00:00 [queued]>
[2022-11-29 01:43:33,770] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 01:43:33,770] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-11-29 01:43:33,770] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 01:43:33,788] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): getDataToLocal> on 2022-11-29 01:43:32.331381+00:00
[2022-11-29 01:43:33,878] {standard_task_runner.py:52} INFO - Started process 829 to run task
[2022-11-29 01:43:33,882] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Covid_dags', 'getDataToLocal', 'manual__2022-11-29T01:43:32.331381+00:00', '--job-id', '774', '--raw', '--subdir', 'DAGS_FOLDER/dbtest.py', '--cfg-path', '/tmp/tmphwbtk3p5', '--error-file', '/tmp/tmpg6l9pm_n']
[2022-11-29 01:43:33,883] {standard_task_runner.py:77} INFO - Job 774: Subtask getDataToLocal
[2022-11-29 01:43:33,938] {logging_mixin.py:109} INFO - Running <TaskInstance: Covid_dags.getDataToLocal manual__2022-11-29T01:43:32.331381+00:00 [running]> on host acb48b0a6e0d
[2022-11-29 01:43:33,988] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Covid_dags
AIRFLOW_CTX_TASK_ID=getDataToLocal
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T01:43:32.331381+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-29T01:43:32.331381+00:00
[2022-11-29 01:43:58,465] {python.py:175} INFO - Done. Returned value was: None
[2022-11-29 01:43:58,474] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=Covid_dags, task_id=getDataToLocal, execution_date=20221129T014332, start_date=20221129T014333, end_date=20221129T014358
[2022-11-29 01:43:58,520] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-29 01:43:58,555] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
