[2022-11-29 01:33:44,702] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: Covid_dags.getDataToLocal manual__2022-11-29T01:33:43.767559+00:00 [queued]>
[2022-11-29 01:33:44,708] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: Covid_dags.getDataToLocal manual__2022-11-29T01:33:43.767559+00:00 [queued]>
[2022-11-29 01:33:44,708] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 01:33:44,708] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-11-29 01:33:44,708] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 01:33:44,717] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): getDataToLocal> on 2022-11-29 01:33:43.767559+00:00
[2022-11-29 01:33:44,720] {standard_task_runner.py:52} INFO - Started process 335 to run task
[2022-11-29 01:33:44,723] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Covid_dags', 'getDataToLocal', 'manual__2022-11-29T01:33:43.767559+00:00', '--job-id', '748', '--raw', '--subdir', 'DAGS_FOLDER/dbtest.py', '--cfg-path', '/tmp/tmp11o9oh_j', '--error-file', '/tmp/tmpojdkip6h']
[2022-11-29 01:33:44,723] {standard_task_runner.py:77} INFO - Job 748: Subtask getDataToLocal
[2022-11-29 01:33:44,762] {logging_mixin.py:109} INFO - Running <TaskInstance: Covid_dags.getDataToLocal manual__2022-11-29T01:33:43.767559+00:00 [running]> on host acb48b0a6e0d
[2022-11-29 01:33:44,797] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Covid_dags
AIRFLOW_CTX_TASK_ID=getDataToLocal
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T01:33:43.767559+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-29T01:33:43.767559+00:00
[2022-11-29 01:34:00,631] {python.py:175} INFO - Done. Returned value was: None
[2022-11-29 01:34:00,708] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=Covid_dags, task_id=getDataToLocal, execution_date=20221129T013343, start_date=20221129T013344, end_date=20221129T013400
[2022-11-29 01:34:00,738] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-29 01:34:00,769] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
